-- Categories for RUBiS database
-- This file has been automatically generated by generate_categories.awk script usingas input file

INSERT INTO categories (name) VALUES ('Antiques & Art ');
INSERT INTO categories (name) VALUES ('Books ');
INSERT INTO categories (name) VALUES ('Business, Office & Industrial ');
INSERT INTO categories (name) VALUES ('Clothing & Accessories ');
INSERT INTO categories (name) VALUES ('Coins ');
INSERT INTO categories (name) VALUES ('Collectibles ');
INSERT INTO categories (name) VALUES ('Computers ');
INSERT INTO categories (name) VALUES ('Consumer Electronics ');
INSERT INTO categories (name) VALUES ('Dolls & Bears ');
INSERT INTO categories (name) VALUES ('Home & Garden ');
INSERT INTO categories (name) VALUES ('Jewelry, Gems & Watches ');
INSERT INTO categories (name) VALUES ('Movies & Television ');
INSERT INTO categories (name) VALUES ('Music ');
INSERT INTO categories (name) VALUES ('Photo ');
INSERT INTO categories (name) VALUES ('Pottery & Glass ');
INSERT INTO categories (name) VALUES ('Sports ');
INSERT INTO categories (name) VALUES ('Stamps ');
INSERT INTO categories (name) VALUES ('Tickets & Travel ');
INSERT INTO categories (name) VALUES ('Toys & Hobbies ');
INSERT INTO categories (name) VALUES ('Everything Else ');
